const schedule = [
  {
    id: 1,
    schedule_date: '2-11-2021',
    start_time: '10 AM',
    end_time: '11 AM',
    rink: 'North Rink',
    event: 'Concordia Men',
    notes: '',
    home_lockerroom: '1',
    visitor_lockerroom: '3',
  },
  {
    id: 2,
    schedule_date: '2-11-2021',
    start_time: '10 AM',
    end_time: '11 AM',
    rink: 'South Rink',
    event: 'Concordia Women',
    notes: '',
    home_lockerroom: '5',
    visitor_lockerroom: '8',
  },
  {
    id: 3,
    schedule_date: '2-11-2021',
    start_time: '12 PM',
    end_time: '1 PM',
    rink: 'North Rink',
    event: 'Yeti Skate',
    notes: '',
    home_lockerroom: '2',
    visitor_lockerroom: '4',
  },
  {
    id: 4,
    schedule_date: '2-11-2021',
    start_time: '1 PM',
    end_time: '2 PM',
    rink: 'South Rink',
    event: 'Milwaukee Power',
    notes: '',
    home_lockerroom: '6',
    visitor_lockerroom: '9',
  },
  {
    id: 5,
    schedule_date: '2-11-2021',
    start_time: '1:30 PM',
    end_time: '2:30 PM',
    rink: 'North Rink',
    event: 'Homestead',
    notes: '',
    home_lockerroom: '1',
    visitor_lockerroom: '3',
  },
  {
    id: 6,
    schedule_date: '2-11-2021',
    start_time: '2:30 PM',
    end_time: '3:30 PM',
    rink: 'South Rink',
    event: 'Cedarburg',
    notes: '',
    home_lockerroom: '5',
    visitor_lockerroom: '8',
  },
  {
    id: 7,
    schedule_date: '2-11-2021',
    start_time: '3:30 PM',
    end_time: '4:30 PM',
    rink: 'North Rink',
    event: 'Lakeshore Lightening',
    notes: '',
    home_lockerroom: '2',
    visitor_lockerroom: '4',
  },
  {
    id: 8,
    schedule_date: '2-11-2021',
    start_time: '3:30 PM',
    end_time: '4:30 PM',
    rink: 'South Rink',
    event: 'Bantam A vs. Bantam B',
    notes: '',
    home_lockerroom: '6',
    visitor_lockerroom: '9',
  },
  {
    id: 9,
    schedule_date: '2-11-2021',
    start_time: '3:30 PM',
    end_time: '4:30 PM',
    rink: 'North Rink',
    event: 'Lakeshore Lightening',
    notes: '',
    home_lockerroom: '2',
    visitor_lockerroom: '4',
  },
  {
    id: 10,
    schedule_date: '2-11-2021',
    start_time: '3:30 PM',
    end_time: '4:30 PM',
    rink: 'South Rink',
    event: 'Bantam A vs. Bantam B',
    notes: '',
    home_lockerroom: '6',
    visitor_lockerroom: '9',
  },
]

export default schedule;
